/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-01-05 16:08:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class _404_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1733294917722L));
    _jspx_dependants.put("/index.jsp", Long.valueOf(1735106431410L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1735106492419L));
    _jspx_dependants.put("jar:file:/D:/Java_Project/Web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Web/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Watches an E-Commerce online Shopping Category Flat\r\n");
      out.write("	Bootstrap Responsive Website Template| Home :: w3layouts</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("	content=\"Watches Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\">\r\n");
      out.write("	 addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } \r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<link href=\"css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<!--webfont-->\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700'\r\n");
      out.write("	rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Dorsa' rel='stylesheet'\r\n");
      out.write("	type='text/css'>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<!-- start menu -->\r\n");
      out.write("<link href=\"css/megamenu.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	media=\"all\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/megamenu.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		$(\".megamenu\").megamenu();\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"js/jquery.easydropdown.js\"></script>\r\n");
      out.write("<script src=\"js/simpleCart.min.js\">\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\"main\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<ul class=\"content-home\">\r\n");
      out.write("				<li class=\"col-sm-4\"><a href=\"single.html\" class=\"item-link\"\r\n");
      out.write("					title=\"\">\r\n");
      out.write("						<div class=\"bannerBox\">\r\n");
      out.write("							<img src=\"images/w1.jpg\" class=\"item-img\" title=\"\" alt=\"\"\r\n");
      out.write("								width=\"100%\" height=\"100%\">\r\n");
      out.write("							<div class=\"item-html\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									Men's<span>Watches</span>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>\r\n");
      out.write("								<button>Shop now!</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"col-sm-4\"><a href=\"single.html\" class=\"item-link\"\r\n");
      out.write("					title=\"\">\r\n");
      out.write("						<div class=\"bannerBox\">\r\n");
      out.write("							<img src=\"images/w3.jpg\" class=\"item-img\" title=\"\" alt=\"\"\r\n");
      out.write("								width=\"100%\" height=\"100%\">\r\n");
      out.write("							<div class=\"item-html\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									Men's<span>Watches</span>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>\r\n");
      out.write("								<button>Shop now!</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"col-sm-4\"><a href=\"single.html\" class=\"item-link\"\r\n");
      out.write("					title=\"\">\r\n");
      out.write("						<div class=\"bannerBox\">\r\n");
      out.write("							<img src=\"images/w2.jpg\" class=\"item-img\" title=\"\" alt=\"\"\r\n");
      out.write("								width=\"100%\" height=\"100%\">\r\n");
      out.write("							<div class=\"item-html\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									Women's<span>Watches</span>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>\r\n");
      out.write("								<button>Shop now!</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<div class=\"clearfix\"></div>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"middle_content\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<h2>Welcome</h2>\r\n");
      out.write("				<p>There are many variations of passages of Lorem Ipsum\r\n");
      out.write("					available, but the majority have suffered alteration in some form,\r\n");
      out.write("					by injected humour, or randomised words which don't look even\r\n");
      out.write("					slightly believable. If you are going to use a passage of Lorem\r\n");
      out.write("					Ipsum, you need to be sure there isn't anything embarrassing hidden\r\n");
      out.write("					in the middle of text. All the Lorem Ipsum generators on the\r\n");
      out.write("					Internet tend to repeat predefined chunks as necessary, making this\r\n");
      out.write("					the first true generator on the Internet. It uses a dictionary of\r\n");
      out.write("					over 200 Latin words, combined with a handful of model sentence\r\n");
      out.write("					structures, to generate Lorem Ipsum which looks reasonable. The\r\n");
      out.write("					generated Lorem Ipsum is therefore always free from repetition,\r\n");
      out.write("					injected humour, or non-characteristic words etc.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"content_middle_bottom\">\r\n");
      out.write("			<div class=\"header-left\" id=\"home\">\r\n");
      out.write("				<section>\r\n");
      out.write("					<ul class=\"lb-album\">\r\n");
      out.write("						<li><a href=\"#image-1\"> <img src=\"images/g1.jpg\"\r\n");
      out.write("								class=\"img-responsive\" alt=\"image01\" /> <span>Pointe</span>\r\n");
      out.write("						</a>\r\n");
      out.write("							<div class=\"lb-overlay\" id=\"image-1\">\r\n");
      out.write("								<a href=\"#page\" class=\"lb-close\">x Close</a> <img\r\n");
      out.write("									src=\"images/g1.jpg\" class=\"img-responsive\" alt=\"image01\" />\r\n");
      out.write("								<div>\r\n");
      out.write("									<h3>\r\n");
      out.write("										pointe <span>/point/</span>\r\n");
      out.write("									</h3>\r\n");
      out.write("									<p>Dance performed on the tips of the toes</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li><a href=\"#image-2\"> <img src=\"images/g2.jpg\"\r\n");
      out.write("								class=\"img-responsive\" alt=\"image02\" /> <span>Port de\r\n");
      out.write("									bras</span>\r\n");
      out.write("						</a>\r\n");
      out.write("							<div class=\"lb-overlay\" id=\"image-2\">\r\n");
      out.write("								<img src=\"images/g2.jpg\" class=\"img-responsive\" alt=\"image02\" />\r\n");
      out.write("								<div>\r\n");
      out.write("									<h3>\r\n");
      out.write("										port de bras <span>/ˌpôr də ˈbrä/</span>\r\n");
      out.write("									</h3>\r\n");
      out.write("									<p>An exercise designed to develop graceful movement and\r\n");
      out.write("										disposition of the arms</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<a href=\"#page\" class=\"lb-close\">x Close</a>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li><a href=\"#image-3\"> <img src=\"images/g3.jpg\"\r\n");
      out.write("								class=\"img-responsive\" alt=\"image03\" /> <span>Plié</span>\r\n");
      out.write("						</a>\r\n");
      out.write("							<div class=\"lb-overlay\" id=\"image-3\">\r\n");
      out.write("								<img src=\"images/g3.jpg\" class=\"img-responsive\" alt=\"image03\" />\r\n");
      out.write("								<div>\r\n");
      out.write("									<h3>\r\n");
      out.write("										pli·é <span>/plēˈā/</span>\r\n");
      out.write("									</h3>\r\n");
      out.write("									<p>A movement in which a dancer bends the knees and\r\n");
      out.write("										straightens them again</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<a href=\"#page\" class=\"lb-close\">x Close</a>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li><a href=\"#image-4\"> <img src=\"images/g4.jpg\"\r\n");
      out.write("								class=\"img-responsive\" alt=\"image04\" /> <span>Adagio</span>\r\n");
      out.write("						</a>\r\n");
      out.write("							<div class=\"lb-overlay\" id=\"image-4\">\r\n");
      out.write("								<img src=\"images/g4.jpg\" class=\"img-responsive\" alt=\"image04\" />\r\n");
      out.write("								<div>\r\n");
      out.write("									<h3>\r\n");
      out.write("										a·da·gio <span>/əˈdäjō/</span>\r\n");
      out.write("									</h3>\r\n");
      out.write("									<p>A movement or composition marked to be played adagio</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<a href=\"#page\" class=\"lb-close\">x Close</a>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li><a href=\"#image-5\"> <img src=\"images/g5.jpg\"\r\n");
      out.write("								class=\"img-responsive\" alt=\"image05\" /> <span>Frappé</span>\r\n");
      out.write("						</a>\r\n");
      out.write("							<div class=\"lb-overlay\" id=\"image-5\">\r\n");
      out.write("								<img src=\"images/g5.jpg\" class=\"img-responsive\" alt=\"image05\" />\r\n");
      out.write("								<div>\r\n");
      out.write("									<h3>\r\n");
      out.write("										frap·pé<span>/fraˈpā/</span>\r\n");
      out.write("									</h3>\r\n");
      out.write("									<p>Involving a beating action of the toe of one foot\r\n");
      out.write("										against the ankle of the supporting leg</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<a href=\"#page\" class=\"lb-close\">x Close</a>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li><a href=\"#image-6\"> <img src=\"images/g6.jpg\"\r\n");
      out.write("								class=\"img-responsive\" alt=\"image06\" /> <span>Glissade</span>\r\n");
      out.write("						</a>\r\n");
      out.write("							<div class=\"lb-overlay\" id=\"image-6\">\r\n");
      out.write("								<img src=\"images/g6.jpg\" class=\"img-responsive\" alt=\"image06\" />\r\n");
      out.write("								<div>\r\n");
      out.write("									<h3>\r\n");
      out.write("										glis·sade <span>/gliˈsäd/</span>\r\n");
      out.write("									</h3>\r\n");
      out.write("									<p>One leg is brushed outward from the body, which then\r\n");
      out.write("										takes the weight while the second leg is brushed in to meet it</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<a href=\"#page\" class=\"lb-close\">x Close</a>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li><a href=\"#image-7\"> <img src=\"images/g7.jpg\"\r\n");
      out.write("								class=\"img-responsive\" alt=\"image07\" /> <span>Jeté</span>\r\n");
      out.write("						</a>\r\n");
      out.write("							<div class=\"lb-overlay\" id=\"image-7\">\r\n");
      out.write("								<img src=\"images/g7.jpg\" class=\"img-responsive\" alt=\"image07\" />\r\n");
      out.write("								<div>\r\n");
      out.write("									<h3>\r\n");
      out.write("										je·té <span>/zhə-ˈtā/</span>\r\n");
      out.write("									</h3>\r\n");
      out.write("									<p>A springing jump made from one foot to the other in any\r\n");
      out.write("										direction</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<a href=\"#page\" class=\"lb-close\">x Close</a>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li><a href=\"#image-8\"> <img src=\"images/g8.jpg\"\r\n");
      out.write("								class=\"img-responsive\" alt=\"image08\" /> <span>Piqué</span>\r\n");
      out.write("						</a>\r\n");
      out.write("							<div class=\"lb-overlay\" id=\"image-8\">\r\n");
      out.write("								<img src=\"images/g8.jpg\" class=\"img-responsive\" alt=\"image08\" />\r\n");
      out.write("								<div>\r\n");
      out.write("									<h3>\r\n");
      out.write("										pi·qué <span>/pēˈkā/</span>\r\n");
      out.write("									</h3>\r\n");
      out.write("									<p>Strongly pointed toe of the lifted and extended leg\r\n");
      out.write("										sharply lowers to hit the floor then immediately rebounds\r\n");
      out.write("										upward</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<a href=\"#page\" class=\"lb-close\">x Close</a>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<div class=\"clearfix\"></div>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</section>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("   	  <div class=\"page-not-found\">\r\n");
      out.write("	    <h1>404</h1>\r\n");
      out.write("	    <a class=\"b-home\" href=\"index.jsp\">back to Home</a>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"footer\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"newsletter\">\r\n");
      out.write("				<h3>Newsletter</h3>\r\n");
      out.write("				<p>Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("					typesetting industry. Lorem Ipsum has been the industry's standard</p>\r\n");
      out.write("				<form>\r\n");
      out.write("					<input type=\"text\" value=\"\" onfocus=\"this.value='';\"\r\n");
      out.write("						onblur=\"if (this.value == '') {this.value ='';}\"> <input\r\n");
      out.write("						type=\"submit\" value=\"SUBSCRIBE\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"cssmenu\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"active\"><a href=\"#\">Privacy</a></li>\r\n");
      out.write("					<li><a href=\"#\">Terms</a></li>\r\n");
      out.write("					<li><a href=\"#\">Shop</a></li>\r\n");
      out.write("					<li><a href=\"#\">About</a></li>\r\n");
      out.write("					<li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<ul class=\"social\">\r\n");
      out.write("				<li><a href=\"\"> <i class=\"instagram\"> </i>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"\"><i class=\"fb\"> </i> </a></li>\r\n");
      out.write("				<li><a href=\"\"><i class=\"tw\"> </i> </a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div class=\"clearfix\"></div>\r\n");
      out.write("			<div class=\"copy\">\r\n");
      out.write("				<p>\r\n");
      out.write("					&copy; 2015 Watches. All Rights Reserved | Design by <a\r\n");
      out.write("						href=\"http://w3layouts.com/\" target=\"_blank\">W3layouts</a>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
